name: CI
on:
  push:
    paths:
      - .github/workflows/ci.yml
      - lib/**
jobs:
  yarn_lint:
    name: python unittest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9.9
      - run: python3 -m unittest discover -s lib -p "*_test.py"
